version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"  # Интерфейс HTTP
      - "50000:50000"  # Для взаимодействия с агентами Jenkins
      - "8443:8443"  # Для HTTPS
    volumes:
      - ./jenkins_home:/var/jenkins_home  # Для сохранения данных Jenkins
      - ./jenkins_ssl:/var/jenkins_ssl  # Для сертификатов
      - /var/run/docker.sock:/var/run/docker.sock  # Для взаимодействия Jenkins с Docker
    environment:
      - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443 --httpsKeyStore=/var/jenkins_ssl/jenkins.p12 --httpsKeyStorePassword=borov2754
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    
    restart: unless-stopped



volumes:
  jenkins_home:
